# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Meng\PyQT5\demo01\loginui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(984, 889)
        LoginWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 371, 531))
        self.frame.setStyleSheet("#frame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(75, 10, 240, 255), stop:1 rgba(255, 0, 0, 255));\n"
"border-radius:20px\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 150, 191, 61))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font :32pt \"黑体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 220, 261, 141))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \"华文细黑\";")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 161, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/document_0.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(400, 40, 371, 491))
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius: 20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 40, 371, 431))
        self.frame_3.setMinimumSize(QtCore.QSize(301, 371))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"}\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    padding-top:5px;\n"
"    padding-left:1px;\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_Register = QtWidgets.QWidget()
        self.page_Register.setObjectName("page_Register")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_Register)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_R_accuont = QtWidgets.QLineEdit(self.page_Register)
        self.lineEdit_R_accuont.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_accuont.setObjectName("lineEdit_R_accuont")
        self.verticalLayout_4.addWidget(self.lineEdit_R_accuont)
        self.lineEdit_R_password_1 = QtWidgets.QLineEdit(self.page_Register)
        self.lineEdit_R_password_1.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_password_1.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_R_password_1.setObjectName("lineEdit_R_password_1")
        self.verticalLayout_4.addWidget(self.lineEdit_R_password_1)
        self.lineEdit_R_password_2 = QtWidgets.QLineEdit(self.page_Register)
        self.lineEdit_R_password_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_password_2.setObjectName("lineEdit_R_password_2")
        self.verticalLayout_4.addWidget(self.lineEdit_R_password_2)
        self.pushButton_R_sure = QtWidgets.QPushButton(self.page_Register)
        self.pushButton_R_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_R_sure.setObjectName("pushButton_R_sure")
        self.verticalLayout_4.addWidget(self.pushButton_R_sure)
        self.stackedWidget_2.addWidget(self.page_Register)
        self.page_Login = QtWidgets.QWidget()
        self.page_Login.setObjectName("page_Login")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_Login)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_L_account = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_L_account.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_account.setObjectName("lineEdit_L_account")
        self.verticalLayout_3.addWidget(self.lineEdit_L_account)
        self.lineEdit_L_password = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_L_password.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_L_password.setObjectName("lineEdit_L_password")
        self.verticalLayout_3.addWidget(self.lineEdit_L_password)
        self.pushButton_L_sure = QtWidgets.QPushButton(self.page_Login)
        self.pushButton_L_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_L_sure.setObjectName("pushButton_L_sure")
        self.verticalLayout_3.addWidget(self.pushButton_L_sure)
        self.stackedWidget_2.addWidget(self.page_Login)
        self.horizontalLayout_3.addWidget(self.stackedWidget_2)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Login = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Login.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Login.setIcon(icon)
        self.pushButton_Login.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.horizontalLayout_2.addWidget(self.pushButton_Login)
        self.pushButton_Register = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Register.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Register.setIcon(icon1)
        self.pushButton_Register.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Register.setObjectName("pushButton_Register")
        self.horizontalLayout_2.addWidget(self.pushButton_Register)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_error = QtWidgets.QWidget()
        self.page_error.setObjectName("page_error")
        self.stackedWidget.addWidget(self.page_error)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_5)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(310, 0, 41, 41))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    border:none;\n"
"}\n"
"#pushButton:hover{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        self.stackedWidget_2.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(LoginWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        LoginWindow.setToolTip(_translate("LoginWindow", "111"))
        self.label.setText(_translate("LoginWindow", "神笔马良"))
        self.label_2.setText(_translate("LoginWindow", "无需复杂配置，直接登录，进行StableDiffusion绘图"))
        self.lineEdit_R_accuont.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.lineEdit_R_password_1.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.lineEdit_R_password_2.setPlaceholderText(_translate("LoginWindow", "确认密码："))
        self.pushButton_R_sure.setText(_translate("LoginWindow", "注册"))
        self.lineEdit_L_account.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.lineEdit_L_password.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.pushButton_L_sure.setText(_translate("LoginWindow", "确认"))
import res_rc
